//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TISWDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Barangay
    {
        public string Barangay_id { get; set; }
        public string Barangay_Districts { get; set; }
        public string Employment { get; set; }
        public string p01 { get; set; }
        public string p02 { get; set; }
        public string p03 { get; set; }
        public string p04 { get; set; }
        public string p05 { get; set; }
        public string p06 { get; set; }
        public string p07 { get; set; }
        public string p08 { get; set; }
        public string p09 { get; set; }
        public string p010 { get; set; }
        public string p011 { get; set; }
        public string p012 { get; set; }
        public string p013 { get; set; }
        public string p013a { get; set; }
        public string p013b { get; set; }
        public string p013c { get; set; }
        public string p013d { get; set; }
        public string p013e { get; set; }
        public string p013f { get; set; }
        public string p014 { get; set; }
        public string p016 { get; set; }
        public string p016course { get; set; }
    }
}
